language: minimal
os: linux
dist: focal

install:
  - pushd /tmp
  - curl -s -O https://niemeyer.s3.amazonaws.com/spread-amd64.tar.gz
  - tar xzvf spread-amd64.tar.gz
  - popd

script:
  - env
  - "/tmp/spread google-nested:"
